# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0003_auto_20160815_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('is done', 'done'), ('in work', 'in work')], default='in work', max_length=10),
        ),
    ]
